BACK-1791: ensure prop IPFS gateway gets used instead of pinata
ourzora/offchain pull request #94
Opened 2023-11-09 18:47 UTC by zylora

## Description

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-11-09 21:30 UTC, mattmalec requested changes

2023-11-09 21:30 UTC, mattmalec commented on offchain/metadata/fetchers/metadata_fetcher.py
> +        from offchain.metadata.pipelines.metadata_pipeline import (
is there a reason to import inside this func?

2023-11-09 21:30 UTC, mattmalec commented on offchain/metadata/fetchers/metadata_fetcher.py
> +            for async_adapter_config in self.async_adapter_configs:
you think this could be slightly rewritten to avoid being deeply nested? also why do we need a for loop with this?

2023-11-10 00:24 UTC, mattmalec approved these changes

2023-11-10 00:24 UTC, mattmalec commented
remember to do the release publishing steps! :)

2023-11-10 02:29 UTC, owen-zora approved these changes

2023-11-10 03:02 UTC, merged